name: secrets
on: [workflow_dispatch]

jobs:
  test_secrets:
    runs-on: ubuntu-latest
#     environment: <env name(for env secret only)>
    steps:
    - name: Log test secrets
      run: |
        token=${{ secrets.REPO_SECRET }}
        echo ${token:0:5}
        echo ${token:5}
